apiVersion: v1
kind: Pod
metadata:
  name: debian-container
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    persistentVolumeClaim:
        claimName: fls-claim

  containers:
  - name: debian-container
    image: debian
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ["-c", "echo Hello from the debian container > /pod-data/index.html"]